[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/catalogo/index.html"
  status = 200
  force = true
  conditions = {Host = ["catalogo.decorandhome.com.mx"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
