import {useEffect,useMemo,useState} from "react";
const MAP="https://maps.app.goo.gl/FQFJXgzCQPDadGgeA";
const cats=[
 {name:"Muros",desc:"Texturas que definen tu estilo",image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85"},
 {name:"Pisos",desc:"Diseño y resistencia para cada espacio",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85"},
 {name:"Deck",desc:"Exterior cálido, durable y contemporáneo",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85"},
 {name:"Pasto y follaje",desc:"Naturaleza y confort todo el año",image:"https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1200&q=85"}];
const products=[
 {id:1,name:"Lambrín WPC Roble",category:"Muros",tag:"Interior",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",desc:"Acabado tipo madera, resistente y de fácil mantenimiento."},
 {id:2,name:"Panel Mármol Ámbar",category:"Muros",tag:"Nuevo",image:"https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=900&q=85",desc:"Veta elegante para muros protagonistas y proyectos comerciales."},
 {id:3,name:"Piso SPC Natural",category:"Pisos",tag:"Favorito",image:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85",desc:"Tecnología resistente al agua con apariencia de madera natural."},
 {id:4,name:"Piso Laminado Siena",category:"Pisos",tag:"Residencial",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85",desc:"Calidez, durabilidad y rápida instalación para renovar tu hogar."},
 {id:5,name:"Deck Sintético Teak",category:"Deck",tag:"Exterior",image:"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=85",desc:"Una superficie durable para terrazas, balcones y jardines."},
 {id:6,name:"Follaje Botánico",category:"Pasto y follaje",tag:"Decorativo",image:"https://images.unsplash.com/photo-1593691509543-c55fb32e5cee?auto=format&fit=crop&w=900&q=85",desc:"Muros verdes con apariencia natural y mínimo mantenimiento."},
 {id:7,name:"Pasto Residencial",category:"Pasto y follaje",tag:"Exterior",image:"https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=85",desc:"Confort visual y práctico para áreas residenciales."},
 {id:8,name:"Panel Acanalado Nogal",category:"Muros",tag:"Tendencia",image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85",desc:"Ritmo, profundidad y diseño contemporáneo para interiores."}];
type Product=(typeof products)[number];
export default function Home(){
 const [menu,setMenu]=useState(false),[active,setActive]=useState("Todos"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Product|null>(null),[quote,setQuote]=useState<Product[]>([]),[drawer,setDrawer]=useState(false);
 const filtered=useMemo(()=>products.filter(p=>(active==="Todos"||p.category===active)&&`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[active,query]);
 const add=(p:Product)=>{setQuote(q=>q.some(x=>x.id===p.id)?q:[...q,p]);setSelected(null);setDrawer(true)};
 const msg=encodeURIComponent(`Hola Decor & Home, me interesa cotizar: ${quote.map(p=>p.name).join(", ")||"materiales para mi proyecto"}.`);
 useEffect(()=>{let ticking=false;const move=()=>{if(!ticking){requestAnimationFrame(()=>{const y=window.scrollY;document.documentElement.style.setProperty("--heroShift",`${Math.min(y*.24,150)}px`);document.documentElement.style.setProperty("--slowShift",`${Math.max(-70,40-y*.055)}px`);ticking=false});ticking=true}};const observer=new IntersectionObserver(items=>items.forEach(i=>i.isIntersecting&&i.target.classList.add("visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));window.addEventListener("scroll",move,{passive:true});move();return()=>{window.removeEventListener("scroll",move);observer.disconnect()}},[]);
 return <main>
  <div className="top">Asesoría para transformar tus espacios <span>·</span> Visítanos en nuestro showroom</div>
  <header><a className="brand" href="#inicio"><img src="/decor-home-logo.png" alt="Decor & Home"/></a><nav className={menu?"open":""}><a href="#productos" onClick={()=>setMenu(false)}>Productos</a><a href="#inspiracion" onClick={()=>setMenu(false)}>Inspiración</a><a href="#nosotros" onClick={()=>setMenu(false)}>Nosotros</a><a href="#ubicacion" onClick={()=>setMenu(false)}>Visítanos</a><button className="navCta" onClick={()=>{setMenu(false);setDrawer(true)}}>Cotiza tu proyecto</button></nav><div className="actions"><button className="quote" onClick={()=>setDrawer(true)}>Cotización <b>{quote.length}</b></button><button className="hamb" onClick={()=>setMenu(!menu)} aria-label="Abrir menú">{menu?"×":"☰"}</button></div></header>
  <section className="hero" id="inicio"><div className="heroPhoto"/><div className="shade"/><div className="heroText"><span className="eyebrow light">Materiales que inspiran</span><h1>Transforma tu espacio.<br/><em>Hazlo tuyo.</em></h1><p>Soluciones en pisos, muros y acabados que combinan diseño, resistencia y personalidad.</p><div className="buttons"><a className="button primary" href="#productos">Ver productos</a><button className="button glass" onClick={()=>setDrawer(true)}>Cotiza tu proyecto</button></div></div><a className="scrollCue" href="#categorias"><span>Descubre</span><i>↓</i></a></section>
  <section className="intro pad reveal"><span className="eyebrow">Encuentra tu estilo</span><div><h2>Soluciones que<br/><em>transforman</em> espacios.</h2><p>Te acompañamos a elegir materiales con carácter, funcionalidad y la apariencia adecuada para cada ambiente.</p></div></section>
  <section className="catGrid pad" id="categorias">{cats.map((c,index)=><button className="cat reveal" style={{transitionDelay:`${index*80}ms`}} key={c.name} onClick={()=>{setActive(c.name);document.getElementById("productos")?.scrollIntoView({behavior:"smooth"})}}><img src={c.image} alt={c.name}/><i/><div><small>Explorar</small><h3>{c.name}</h3><p>{c.desc}</p></div><b>↗</b></button>)}</section>
  <section className="catalog pad" id="productos"><div className="heading"><div><span className="eyebrow">Nuestro catálogo</span><h2>Materiales para cada idea.</h2></div><label className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar material..."/></label></div><div className="filters">{["Todos",...cats.map(c=>c.name)].map(x=><button className={active===x?"active":""} key={x} onClick={()=>setActive(x)}>{x}</button>)}</div><div className="productGrid">{filtered.map(p=><article key={p.id}><button className="productImage" onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><span>{p.tag}</span><b>Ver detalle</b></button><div className="productInfo"><div><small>{p.category}</small><h3>{p.name}</h3></div><button onClick={()=>add(p)}>+</button></div></article>)}</div>{!filtered.length&&<p className="empty">No encontramos materiales con esa búsqueda.</p>}</section>
  <section className="experience" id="inspiracion"><div className="expImage" role="img" aria-label="Interior contemporáneo con acabados de madera natural"/><div className="expCopy"><span className="eyebrow light">Diseña con confianza</span><h2>De la inspiración a un espacio <em>real.</em></h2><p>Cuéntanos qué quieres renovar. Te ayudamos a comparar acabados, calcular materiales y elegir la solución adecuada.</p><div className="steps"><span><b>01</b> Comparte tu idea</span><span><b>02</b> Elige tu material</span><span><b>03</b> Recibe tu cotización</span></div><button className="button cream" onClick={()=>setDrawer(true)}>Comenzar mi proyecto</button></div></section>
  <section className="about pad" id="nosotros"><div><span className="eyebrow">Decor & Home</span><h2>Diseño que se siente<br/>como <em>hogar.</em></h2><p>Somos especialistas en materiales para decoración interior y exterior. Seleccionamos soluciones versátiles para hogares, comercios y proyectos profesionales.</p><ul><li>Asesoría personalizada</li><li>Variedad de texturas y acabados</li><li>Soluciones para interior y exterior</li></ul></div><div className="aboutImage"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85" alt="Interior contemporáneo"/><span><b>Tu proyecto</b> merece una gran primera impresión.</span></div></section>
  <section className="location" id="ubicacion"><div><span className="eyebrow light">Ven a conocernos</span><h2>Descubre materiales, texturas y posibilidades.</h2><p>Visita Decor & Home y recibe atención personalizada para tu proyecto.</p><a className="button cream" href={MAP} target="_blank">Abrir en Google Maps ↗</a></div><a className="map" href={MAP} target="_blank" aria-label="Abrir ubicación de Decor & Home en Google Maps"><i>⌖</i><span>Decor & Home</span><small>Abrir ubicación</small></a></section>
  <footer><img src="/decor-home-logo.png" alt="Decor & Home"/><p>Materiales para espacios con identidad.</p><div><a href="#productos">Productos</a><a href="#nosotros">Nosotros</a><a href={MAP} target="_blank">Ubicación</a></div><small>© 2026 Decor & Home. Todos los derechos reservados.</small></footer>
  <button className="floating" onClick={()=>setDrawer(true)}>✦ <span>Cotizar proyecto</span>{quote.length>0&&<b>{quote.length}</b>}</button>
  <div className="mobileCtas"><a href="#productos"><small>Explorar</small>Catálogo</a><a href={MAP} target="_blank"><small>Visitar</small>Ubicación</a><button onClick={()=>setDrawer(true)}><small>Contacto</small>Cotizar {quote.length>0&&<b>{quote.length}</b>}</button></div>
  {selected&&<div className="modalWrap" onClick={()=>setSelected(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={selected.name}/><div><small>{selected.category} · {selected.tag}</small><h2>{selected.name}</h2><p>{selected.desc}</p><button className="button primary" onClick={()=>add(selected)}>Agregar a cotización</button></div></article></div>}
  <aside className={drawer?"drawer open":"drawer"}><div className="drawerHead"><div><small>Tu selección</small><h2>Solicita una cotización</h2></div><button onClick={()=>setDrawer(false)}>×</button></div><p>Agrega materiales y envíanos tu lista para recibir asesoría.</p><div className="quoteList">{quote.map(p=><div key={p.id}><img src={p.image} alt=""/><span>{p.name}<small>{p.category}</small></span><button onClick={()=>setQuote(quote.filter(x=>x.id!==p.id))}>×</button></div>)}{!quote.length&&<div className="emptyQuote">Aún no has agregado productos.</div>}</div><a className="button primary full" href={`https://wa.me/?text=${msg}`} target="_blank">Enviar por WhatsApp</a><button className="continue" onClick={()=>setDrawer(false)}>Seguir explorando</button></aside>{drawer&&<button className="backdrop" onClick={()=>setDrawer(false)}/>} 
 </main>}
